spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect