spring:
  datasource:
    url: ${DATABASE_JDBC_URL}
    username: ${DATABASE_USER_NAME}
    password: ${DATABASE_PASSOWORD}
    driver-class-name: {DATABASE_DRIVER}
  jpa:
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect